### PR TITLE
Deleting release-nocmake

### PR DESCRIPTION
**Pull request by edorossi**
Do we still want this?

### CODE REVIEW

**Comment by jha92** [comment]
Hi Edo.
No point to touch this now, we will focus on the new master with complete new installation. Will see if this survives.
More next week.

**Comment by edorossi** [comment]
I totally of not touching it now, it is a sort of WIP :)

**Comment by jha92** [comment]
Sure, was only to make you aware of the new developments in master and to be there the more appropiate location to work on :)

**Comment by jha92** [comment]
Hi, I did it now only a version with nocmakenoroot for the local installation. Still to be tested on local infrastructure.

**Pull request closed without merging**
